url: https://atamahjoubfar.github.io
baseurl: 
timezone: America/Los_Angeles

# Site settings
title: Amir Matin
email: amiralimtn@gmail.com
description: "This is Amir Matin's personal website..."

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: fed136
  secondary: fec503  
  secondary-dark: 333

# Team names, titles and social links
people:
- name: Amir Matin
  pic: 1
  position: Data Scientist

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: linkedin
    url: https://uk.linkedin.com/in/amirali-matin-78392951

